    jwt:
      secret: AP/mTtG2INNS9nS/dz4kT+Lxo+Au4PhjfXE09zLKaZs=
      lifetime: 30m

    spring:
      datasource:
        url: jdbc:postgresql://185.125.91.161:5432/prodtest
        username: postgres
        password: 1234
        driver-class-name: org.postgresql.Driver

      jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
        properties:
          hibernate:
            format_sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
      flyway:
        baseline-on-migrate: true
        mixed: false

      main:
        allow-circular-references: true

  server:
    port: 8001